### ISSUE TITLE
GitHub Actionsへ移行

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text_pdf#17]
本体は移行した
https://github.com/scala-text/scala_text/issues/574

**Comment by xuwei-k** [comment]
Travis CIに設定してるsecretな変数をこっちに設定してもらえば、他の人でも移行できそう。

(逆に言うと、全く同じ仕組みにするなら、その変数設定してもらわない限り、移行ができない？)
(なにがsecretにしてあるんだっけ・・・)

https://github.com/scala-text/scala_text_pdf/blob/677815194d6ed01462e673c577104c7ce49bd985/.travis.yml#L39-L40
https://github.com/scala-text/scala_text_pdf/settings/secrets/actions

**Comment by y-yu** [comment]
これはたぶん

- push用の暗号化ずみ秘密鍵の対称鍵
- Docker Hubのキー

ですね。たぶん前者は使わなくてもよくなりそうなんで、ちょっとやってみるか。
