### ISSUE TITLE
JDK 11へupdate

### ISSUE THREAD

**Issue by xuwei-k** [scala-text/scala_text_pdf#66]
- こっちで11必須にしたらpdfのbuild壊れた 😇 https://github.com/scala-text/scala_text/pull/1255#issuecomment-1800937257

ここ上げればいいんだっけ・・・？ 🤔 

https://github.com/scala-text/scala_text_pdf/blob/a4f62c40f231525a0dfe6233288b524249c517df/docker/Dockerfile#L10

**Comment by y-yu** [comment]
おっ、それでよさそう 🙆‍♀️
